// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrkPMDTDv7KHGNiZKAU9IVhZ96jCLMEQ',
    appId: '1:876358720622:web:84c01ff6fdd113bb525a7f',
    messagingSenderId: '876358720622',
    projectId: 'bookseven-test',
    authDomain: 'bookseven-test.firebaseapp.com',
    databaseURL: 'https://bookseven-test-default-rtdb.firebaseio.com',
    storageBucket: 'bookseven-test.appspot.com',
    measurementId: 'G-R9V4EPHGQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVlAmQSTY-4pGKV7I1rC6z9kPuxKovYY',
    appId: '1:876358720622:android:129f1244d7374cd7525a7f',
    messagingSenderId: '876358720622',
    projectId: 'bookseven-test',
    databaseURL: 'https://bookseven-test-default-rtdb.firebaseio.com',
    storageBucket: 'bookseven-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfr2qfOkWTRSWdEu5osv9j1CudwnkuIFA',
    appId: '1:876358720622:ios:ba841603003455dd525a7f',
    messagingSenderId: '876358720622',
    projectId: 'bookseven-test',
    databaseURL: 'https://bookseven-test-default-rtdb.firebaseio.com',
    storageBucket: 'bookseven-test.appspot.com',
    iosClientId: '876358720622-vagc7qdc47iriu54ts3bhnvpcd6s87bg.apps.googleusercontent.com',
    iosBundleId: 'com.alisutech.bookseven',
  );
}